name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts/
          packages_with_index: true
        env:
            CR_TOKEN: "${{ secrets.CHART_RELEASER_TOKEN }}"
            CR_PACKAGES_WITH_INDEX: true

  
        